name: n8n

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Install and Run n8n with Cloudflared
        run: |
          # Install & Run n8n (Background)
          sudo npm i -g n8n
          N8N_BASIC_AUTH_ACTIVE=true N8N_BASIC_AUTH_USER=admin N8N_BASIC_AUTH_PASSWORD=admin nohup n8n start &

          # Tunggu 3 menit
          sleep 180

          # Install Cloudflared dan jalankan Tunnel
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o cf.deb
          sudo dpkg -i cf.deb
          cloudflared tunnel --url http://localhost:5678
